name: Publish Release

on:
  workflow_dispatch:


jobs:
  check_triggering_actor:
    name: Check user is allowed to create release
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ github.triggering_actor }}" != "ahoppen" ]]; then
            echo "${{ github.triggering_actor }} is not allowed to create a release"
            exit 1
          fi
  define_tags:
    name: Determine dependent swift-syntax version and prerelease date
    runs-on: ubuntu-latest
    outputs:
      swift_syntax_tag: ${{ steps.swift_syntax_tag.outputs.swift_syntax_tag }}
      swift_format_version: ${{ steps.swift_format_version.outputs.swift_format_version }}
    steps:
    - name: Determine swift-syntax tag to depend on
      id: swift_syntax_tag
      run: echo "swift_syntax_tag=601.0.0-prerelease-2024-09-25" >> "$GITHUB_OUTPUT"
    - name: Determine swift-format prerelease version
      id: swift_format_version
      run: echo "swift_format_version=601.0.0-prerelease-$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"
  test_release:
    name: Test in Release configuration
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    needs: define_tags
    with:
      exclude_swift_versions: '[{"swift_version": "5.8"}, {"swift_version": "5.9"}, {"swift_version": "5.10"}, {"swift_version": "nightly-6.0"}, {"swift_version": "nightly-main"}]'
      pre_build_command: bash .github/workflows/create-release-commits.sh '${{ needs.define_tags.outputs.swift_syntax_tag }}' '${{ needs.define_tags.outputs.swift_format_version }}'
  publish_release:
    name: Create Tag
    runs-on: ubuntu-latest
    needs: [define_tags, test_release, check_triggering_actor]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create release commits
      run: bash .github/workflows/create-release-commits.sh '${{ needs.define_tags.outputs.swift_syntax_tag }}' '${{ needs.define_tags.outputs.swift_format_version }}'
    - name: Tag release
      run: |
        git tag "${{ needs.define_tags.outputs.swift_format_version }}"
        git push origin "${{ needs.define_tags.outputs.swift_format_version }}"
