name: publish_release

on:
  workflow_dispatch:


jobs:
  test_debug:
    name: Test in Debug configuration
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      exclude_swift_versions: '[{"swift_version": "5.8"}, {"swift_version": "5.9"}, {"swift_version": "5.10"}, {"swift_version": "nightly-6.0"}]'
      build_command: "swift test"
  test_release:
    name: Test in Release configuration
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      exclude_swift_versions: '[{"swift_version": "5.8"}, {"swift_version": "5.9"}, {"swift_version": "5.10"}, {"swift_version": "nightly-6.0"}]'
      build_command: "swift test -c release"
  publish_release:
    name: publish_release
    runs-on: ubuntu-latest
    needs: [test_debug, test_release]
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Tag release
      run: |
        TAG_NAME="601.0.0-prerelease-${{ steps.date.outputs.date }}"
        git tag "$TAG_NAME"
        git push origin "$TAG_NAME"


    # - name: Release snapshot
    #   id: release-snapshot
    #   uses: actions/create-release@latest
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: "600.0.0-prerelease-${{ steps.date.outputs.date }}"
    #     release_name: "600.0.0-prerelease-${{ steps.date.outputs.date }}"
    #     draft: false
    #     prerelease: true
