name: publish_release

on:
  workflow_dispatch:


jobs:
  publish_release:
    name: publish_release
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Release snapshot
      id: release-snapshot
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "600.0.0-prerelease-${{ steps.date.outputs.date }}"
        release_name: "600.0.0-prerelease-${{ steps.date.outputs.date }}"
        draft: false
        prerelease: true
