name: publish_release

on:
  workflow_dispatch:


jobs:
  publish_release:
    name: publish_release
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Tag release
      run: |
        git config --global user.name 'swift-ci'
        git config --global user.email 'swift-ci@users.noreply.github.com'
        # git commit -am "Automated report"
        TAG_NAME="601.0.0-prerelease-${{ steps.date.outputs.date }}"
        git tag "$TAG_NAME"
        git push origin "$TAG_NAME"
