name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    uses: ahoppen/github-workflows/.github/workflows/swift_package_test.yml@cross-pr-testing
    with:
      enable_cross_pr_testing: true
  # soundness:
  #   name: Soundness
  #   uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
  #   with:
  #     license_header_check_enabled: false
  #     license_header_check_project_name: "Swift.org"
